/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.importdata.view;

import com.importdata.controller.Controle;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author jrcsilva
 */
public class Janela extends javax.swing.JFrame {

    Controle controle = new Controle();
    
    /**
     * Creates new form Janela
     */
    public Janela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btTransferir = new javax.swing.JButton();
        txtCaminhoHDFS = new javax.swing.JTextField();
        txtNomeArquivo = new javax.swing.JTextField();
        txtDiretorio = new javax.swing.JTextField();
        labelDiretorio = new javax.swing.JLabel();
        labelEscala = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelDiretorioListar = new javax.swing.JLabel();
        txtDiretorioListar = new javax.swing.JTextField();
        btListar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txtDiretorioRemover = new javax.swing.JTextField();
        labelDiretorioRemover = new javax.swing.JLabel();
        btRemover = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        txtDiretorioLer = new javax.swing.JTextField();
        btLer = new javax.swing.JButton();
        labelDiretorioLer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IMPORTADOR");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTitulo.setText("IMPORTADOR DE ARQUIVOS HDFS");

        btTransferir.setText("Transferir");
        btTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTransferirActionPerformed(evt);
            }
        });

        txtNomeArquivo.setMaximumSize(new java.awt.Dimension(360, 360));

        txtDiretorio.setMaximumSize(new java.awt.Dimension(360, 360));

        labelDiretorio.setText("Diretório Arquivo");

        labelEscala.setText("Nome do Arquivo");

        jLabel2.setText("Caminho no HDFS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelDiretorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(labelEscala))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btTransferir)
                                .addGap(0, 347, Short.MAX_VALUE))
                            .addComponent(txtCaminhoHDFS)
                            .addComponent(txtNomeArquivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiretorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiretorio))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeArquivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelEscala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCaminhoHDFS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btTransferir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Transferir", jPanel1);

        labelDiretorioListar.setText("Diretório");

        txtDiretorioListar.setMaximumSize(new java.awt.Dimension(360, 360));

        btListar.setText("Listar");
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDiretorioListar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btListar)
                        .addGap(0, 437, Short.MAX_VALUE))
                    .addComponent(txtDiretorioListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiretorioListar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiretorioListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btListar)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar Diretórios e Arquivos", jPanel2);

        txtDiretorioRemover.setMaximumSize(new java.awt.Dimension(360, 360));
        txtDiretorioRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiretorioRemoverActionPerformed(evt);
            }
        });

        labelDiretorioRemover.setText("Diretório");

        btRemover.setText("Remover");
        btRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDiretorioRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btRemover)
                        .addGap(0, 417, Short.MAX_VALUE))
                    .addComponent(txtDiretorioRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiretorioRemover, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiretorioRemover))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btRemover)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Remover Diretório", jPanel3);

        txtDiretorioLer.setMaximumSize(new java.awt.Dimension(360, 360));

        btLer.setText("Ler");
        btLer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLerActionPerformed(evt);
            }
        });

        labelDiretorioLer.setText("Diretório");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDiretorioLer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btLer)
                        .addGap(0, 449, Short.MAX_VALUE))
                    .addComponent(txtDiretorioLer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiretorioLer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDiretorioLer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLer)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ler Arquivo", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(labelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTransferirActionPerformed
        btTransferir.setEnabled(false);
        if(this.txtDiretorio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Diretório - Preenchimento Obrigatório", null, JOptionPane.ERROR_MESSAGE);
            return;
        }

        if(this.txtNomeArquivo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nome do Arquivo - Preenchimento Obrigatório", null, JOptionPane.ERROR_MESSAGE);
            return;   
        }

        if(this.txtCaminhoHDFS.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Caminho no HDFS - Preenchimento Obrigatório", null, JOptionPane.ERROR_MESSAGE);
            return;   
        }

        try {
            String returno = controle.transferDataForHDFS(
                    this.txtDiretorio.getText(),
                    this.txtNomeArquivo.getText(),
                    this.txtCaminhoHDFS.getText()
            );


            JOptionPane.showMessageDialog(null, returno);
            btTransferir.setEnabled(true);
        } catch (IOException ex) {
            btTransferir.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado.");
            
            ex.printStackTrace();
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            btTransferir.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado.");
            
            ex.printStackTrace();
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btTransferirActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
        btListar.setEnabled(false);
        if(this.txtDiretorioListar.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Diretório - Preenchimento Obrigatório", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            String returno = controle.listFilesAndDirectoriesByDirectory(this.txtDiretorioListar.getText());
            JOptionPane.showMessageDialog(this, returno);
            btListar.setEnabled(true);
        } catch (Exception ex) {
            btTransferir.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado.");
            
            ex.printStackTrace();
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btListarActionPerformed

    private void btRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverActionPerformed
        btRemover.setEnabled(false);
        if(this.txtDiretorioRemover.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Diretório - Preenchimento Obrigatório", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            controle.removeDirectory(this.txtDiretorioRemover.getText());
            JOptionPane.showMessageDialog(null, "Diretório removido com sucesso.");
            btRemover.setEnabled(true);
        } catch (Exception ex) {
            btRemover.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado.");
            
            ex.printStackTrace();
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btRemoverActionPerformed

    private void btLerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLerActionPerformed
        btLer.setEnabled(false);
        if(this.txtDiretorioLer.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Diretório - Preenchimento Obrigatório", null, JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            controle.readFile(this.txtDiretorioLer.getText());
            JOptionPane.showMessageDialog(null, "Sucesso! Veja o log.");
            btLer.setEnabled(true);
        } catch (Exception ex) {
            btLer.setEnabled(true);
            JOptionPane.showMessageDialog(null, "Ocorreu um erro inesperado.");
            
            ex.printStackTrace();
            Logger.getLogger(Janela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btLerActionPerformed

    private void txtDiretorioRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiretorioRemoverActionPerformed
        
    }//GEN-LAST:event_txtDiretorioRemoverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        try{               
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch(Exception e){
               System.out.println("Não foi possível alterar a L&F");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Janela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLer;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btRemover;
    private javax.swing.JButton btTransferir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelDiretorio;
    private javax.swing.JLabel labelDiretorioLer;
    private javax.swing.JLabel labelDiretorioListar;
    private javax.swing.JLabel labelDiretorioRemover;
    private javax.swing.JLabel labelEscala;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JTextField txtCaminhoHDFS;
    private javax.swing.JTextField txtDiretorio;
    private javax.swing.JTextField txtDiretorioLer;
    private javax.swing.JTextField txtDiretorioListar;
    private javax.swing.JTextField txtDiretorioRemover;
    private javax.swing.JTextField txtNomeArquivo;
    // End of variables declaration//GEN-END:variables
}
